name: CI

on:
  workflow_dispatch:
  push:
    branches: ["*"]
#  pull_request:
#    branches: [ "*" ]

jobs:
  check:
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - uses: huanshankeji/.github/workflow-templates/gradle-check@refactor-common-actions
        with:
          jdk-versions: 8-zulu

  dependency-submission:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: huanshankeji/.github/workflow-templates/dependency-submission@refactor-common-actions
        with:
          jdk-version: 8
          jdk-distribution: zulu
