name: CI

on:
  workflow_dispatch:
  push:
    branches: ["*"]
#  pull_request:
#    branches: [ "*" ]

jobs:
  test-and-check:
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - uses: huanshankeji/.github/actions/gradle-test-and-check@composite-actions-add-gradle-test
        with:
          jdk-versions: 8-zulu

  dependency-submission:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: huanshankeji/.github/actions/dependency-submission@composite-actions-add-gradle-test
        with:
          jdk-version: 8
          jdk-distribution: zulu
